name: example
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  cupertino_icons: ^1.0.5
  flutter_svg: any
  permission_handler: any
  provider: any
  another_flushbar: ^1.12.29
  qr_code_scanner: ^1.0.1
  http: any


  video_stream:
    path: ../

  wakelock: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1


flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/svg/