name: video_stream
description: A new Flutter package to live stream video to RTMP server.
version: 0.0.1
homepage: https://github.com/PRETOLIO-DEV/rtmp_video_stream

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  stream_transform: ^2.1.0

dev_dependencies:
  path_provider: ^2.0.11
  video_player: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.marshalltechnology.video_stream
        pluginClass: RtmppublisherPlugin
      ios:
        pluginClass: FlutterRtmpPlugin
